before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq tmux zsh git
install: script/cached-bundle install --deployment --without development --jobs 3 --retry 3
script: script/test
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
notifications:
  email: false
env:
  global:
    - AMAZON_S3_BUCKET=ci-cache
    - AMAZON_ACCESS_KEY_ID=AKIAJQCVTDEWQHRPBPGQ
    - secure: "XAZv5xyNjWt7F9hG0MZhDANVJ5h/ajEZvfJOEIZRQlE3X5x6oVgI8blLh/MmlRSF0kIyLckcn6t2ccjSOvwN2hca5bwZSjIqoKbJyNe2cmkxfi2432vEOu3Ve6PT5hZWX4R5RgT+xWyMjIJcdF3gUMP7ErXl64aEncBzeW6OoXM="
